name: "Godot Export and Upload"
on: push
#env:
#  GODOT_VERSION: 4.2
#  EXPORT_NAME: tile-jumper-exodus
  
jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    steps:
      - id: commit-type
        name: Check Commit Type
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^\d*$'
          error: 'The commit message does not look like a version number. Please use semantic versioning (https://semver.org/).'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Find and Replace Version
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "__TJE_VERSION__"
          replace: ${{ github.event.head_commit.message }}
          regex: false

      - name: export game
        id: export
        # Use latest version (see releases for all versions)
        uses: firebelley/godot-export@v5.2.0
        with:
            # Defining all the required inputs
            godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.1/Godot_v4.1-stable_linux.x86_64.zip
            godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.1/Godot_v4.1-stable_export_templates.tpz
            relative_project_path: ./
            archive_output: false

      - name: test
        run: |
          ls
          ls build
          ls "build/web"
            
      - name: Upload to itch.io
        uses: dulvui/itchio-butler-upload@v0.0.1
        with:
            working-directory: "build/web/web.zip"
            api-key: ${{ secrets.BUTLER_CREDENTIALS }}
            user: maximino
            game: tile-jumper-exodus
            channel: html5