name: itch.io upload

# define what triggers the action
# in this case: on push if one of the files named in paths changes
on:
  push:
    branches:
      - master

jobs:
  deploy:
    # only run action, if pushed on prod branch
    # change or remove according to your needs
    runs-on: ubuntu-20.04
    container:
        image: barichello/godot-ci:3.3.4
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      
      # change or remove according to your needs
      - name: Create export directory
        run: mkdir html5

      - name: Godot HTML5 export
        run: | 
            mkdir html5
            godot -v --export-release "HTML5" html5/index.html

      # uploads to itch.io
      # more info here https://github.com/dulvui/itchio-butler-upload
      - name: Upload to itch.io
        uses: dulvui/itchio-butler-upload@v0.0.1
        with:
          working-directory: html5
          api-key: ${{ secrets.BUTLER_CREDENTIALS }}
          user: maximino
          game: tile-jumper-exodus
          channel: html5